### ISSUE TITLE
Reduce TLS overhead.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/universal-search-recommendation#115] opened 2016-04-29 23:47 UTC
Migrating from discussion here: https://github.com/mozilla/universal-search/issues/122

> I would say the lowest hanging fruit would be to look at moving the TLS overhead. Perhaps going to http/2 we make a single tls connection and reuse it. This is a longer design discussion as it's a non trivial change to make. 

Let's do that! Let me know if there's any engineering work that needs to be done for this; I'd be happy to assist.

**Comment by mostlygeek** [comment] 2016-04-29 23:52
Does this really block the public launch?

**Comment by chuckharmston** [comment] 2016-04-29 23:54
I would think so. Our target has been the speed with which we get results from Yahoo for search suggestions, and those are coming in about 150ms faster for me ([data](https://github.com/mozilla/universal-search/issues/122#issuecomment-214831760)).

That's ultimately @nchapman's call, though.

**Comment by 6a68** [comment] 2016-04-30 01:05
I think we might want to investigate this further before proposing that it block public launch.

"X fast on my laptop" does not seem like a solid approach to measuring server performance. We need a way to measure the latency that is the same for everyone involved. (Are we measuring latency over a cold or warmed connection?)

Here's a suggestion: measure latency by averaging 5 requests from the default webpagetest.org location, using Firefox, but keeping other settings at defaults. This website is accessible to everybody, and the result URLs are durable. I'm not sure how to get at the TLS numbers, but there is plenty of detail to dig through (raw HAR files and detail views on the website).

With settings that look like this:

<img width="951" alt="screen shot 2016-04-29 at 5 57 29 pm" src="https://cloud.githubusercontent.com/assets/96396/14932907/23765b0e-0e34-11e6-933a-c4376c0cafba.png">

The results are here: http://www.webpagetest.org/result/160430_X3_6Z5/

Assuming this way of measuring works for everyone, we need to pick a number to optimize (is 'document complete' a good enough proxy?), and then figure out how to get that number to some goal number as cheaply as possible. And then actually do the work.

To me, this seems like a pretty big project to tackle this close to launch. What do you two think? Maybe @wresuolc has thoughts as well.

**Comment by 6a68** [comment] 2016-04-30 01:06
Ah, looking at chuck's last comment, we could measure yahoo's search suggestions API from the same webpagetest.org location, and use that as the number we want to reach.

**Comment by chuckharmston** [comment] 2016-04-30 01:16
> Ah, looking at chuck's last comment, we could measure yahoo's search suggestions API from the same webpagetest.org location, and use that as the number we want to reach.

Yeah, that's why I'm okay with "from my laptop" as a rudimentary measure—I'm making a relative comparison to Yahoo's results from the same machine.

Yahoo's results, for comparison: http://www.webpagetest.org/result/160430_VZ_93D/

Surprisingly comparable, although it's not a perfect test case; it doesn't really simulate our use case of "lots of requests from the same connection in relatively quick succession".

**Comment by 6a68** [comment] 2016-04-30 01:44
Yeah, that totally makes sense. Still, would be nice to have fixed numbers, vs. a percentage or ratio.

**Comment by wresuolc** [comment] 2016-04-30 01:59
> Does this really block the public launch? The public launch is May 9th right?

May 10th.  This was the alternative we (Travis and I, so it might have been lost in the shuffle) talked about instead of paying a CDN with http/2 support.  How much work/effort is it to enable on our server?

Thanks

**Comment by mostlygeek** [comment] 2016-04-30 07:30
After a bit of digging into H2 and looking at the requirements more I retract my suggestion to enable H2. HTTP 1.1 keepalive are good enough: 

```bash
> HOST=universalsearch.testpilot.firefox.com; curl -s -w "%{time_connect} %{time_appconnect} %{time_starttransfer} %{time_total}\n" \
    -o /dev/null https://$HOST/?q=f  \
    -o /dev/null https://$HOST/?q=fi  \
    -o /dev/null https://$HOST/?q=fir  \
    -o /dev/null https://$HOST/?q=fire  \
    -o /dev/null https://$HOST/?q=firef  \
    -o /dev/null https://$HOST/?q=firefo  \
    -o /dev/null https://$HOST/?q=firefox

0.554 0.706 0.742 0.742
0.000 0.000 0.027 0.027
0.000 0.000 0.028 0.028
0.000 0.000 0.027 0.027
0.000 0.000 0.027 0.027
0.000 0.000 0.026 0.026
0.000 0.000 0.026 0.026
```
In the example above using curl, I simulated typing out "firefox". HTTP 1.1 persistent connections is fast and already works. 

After the expensive initial TLS connection each additional query is less than 30ms. Most of that 30ms is network RTT and likely a nginx cache hit is <1ms of the total time. 

I'm actually not sure if it is possible to have firefox replicate the curl example with XHRs. I'm guessing that each XHR will be a new connect/tls/request. I also don't know if Firefox's H2 behavior would be any different. Somebody who has intimate knowledge of the network stack would have to weigh in here.

**Comment by mostlygeek** [comment] 2016-04-30 07:40
I tried out google's instance search on google.ca. It uses H2 and the initial connection is slow (~150ms) but each additional character type is only ~60ms. Not sure if this is purely H2 or if it is another javascript technique under the covers. 

Can somebody try it out with universal-search and paste what the network XHR timings look like?

**Comment by nchapman** [comment] 2016-05-02 17:43
I don't know about the technical details here, but I agree with Chuck about matching the search suggestions speed (assuming those are over https). I did a bunch of testing over the weekend and the perceived performance of the current version seemed pretty great, so it seems like if we have some kind of piplining then that's good enough for the launch.

**Comment by chuckharmston** [comment] 2016-05-02 18:18
I guess we're removing the public launch flag this based on @nchapman's comment, and wontfixing based on @mostlygeek's assertion in IRC:

> i don't think H2 will give you guys anything extra for performance

I guess this would be wontfixed. Assigning to @clouserw to verify.

**Comment by wresuolc** [comment] 2016-05-02 18:36
How much work are we talking about to verify that H2 does or doesn't help us?  I don't think we should wontfix this without hard numbers.  It would be great to say "we tried H/2 and it didn't do anything" or "we tried H/2 and for some reason handshakes were way faster but it didn't work well for our tiny packets" or whatever.  If we don't try it we're all just guessing, right?

**Comment by mostlygeek** [comment] 2016-05-02 19:25
chuck helped me get the add-on installed and [enabling dev tools to see what it's doing](https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox).

It's rather difficult to actually debug the network traffic for the addon. You have to clear the browser's cache and then start typing. Even then, I'm not sure the network results are always consistent. However, I've been able to reproduce this fairly consistently with: 

1. start dev tools
2. start typing in the location bar 
3. watch the network requests
4. clear the cache and wait a couple of minutes (for connections to close?)
5. repeat

This is the first request, it has a long connection time. Likely due to TLS;

![screen shot 2016-05-02 at 11 05 39 am](https://cloud.githubusercontent.com/assets/83972/14962962/4d40222a-1056-11e6-8e50-4f6946b3c0d1.png)

The immediate second request, 32ms. 

![screen shot 2016-05-02 at 11 06 07 am](https://cloud.githubusercontent.com/assets/83972/14962969/56f1814c-1056-11e6-9e60-11504d0f5ee0.png)

The last request, also 32ms. 

![screen shot 2016-05-02 at 11 06 32 am](https://cloud.githubusercontent.com/assets/83972/14962972/5ccc4a3e-1056-11e6-8ac8-accccc347506.png)

From these tests there doesn't seem to be any TLS overhead for additional queries.

**Comment by mostlygeek** [comment] 2016-05-02 19:28
It would be good if somebody else can try the same test to see if my results are reproducible.

**Comment by wresuolc** [comment] 2016-05-03 22:29
I tried it.  My Connecting time was only on the first query, like yours (although it was substantially shorter), and the subsequent queries were all 0ms except for Waiting which was around 30-40ms.

So, I agree this doesn't block launch.  I don't know enough about H/2 to know if it would help us here or not though.  @chuckharmston do you think it would improve the numbers more?

**Comment by 6a68** [comment] 2016-05-04 01:10
Just want to mention that you can optionally disable caching when the Browser Toolbox is open by hitting the gear icon at top right, then it's the second checkbox under 'Advanced settings':

<img width="911" alt="screen shot 2016-05-03 at 6 08 48 pm" src="https://cloud.githubusercontent.com/assets/96396/15002830/3a1142a6-115a-11e6-8316-f9f8f5be5ea4.png">

Browser Toolbox docs: https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox

**Comment by chuckharmston** [comment] 2016-05-04 14:45
Yeah, I'm with Jared; 0ms sounds like browser-level caching to me. It's great that we can take advantage of that, but I don't think it satisfies this story.

**Comment by mostlygeek** [comment] 2016-05-11 22:24
Closing this issue as HTTP pipelining already reduces TLS overhead. Looking at the nginx logs during testing nginx+python was < 5 milliseconds. Cached nginx results were <1ms. Cache browser results = 0ms (like hundreds of microseconds). Most of the time is spent in network RTT between users and us-west-2.

**Closed by mostlygeek** 2016-05-11 22:24 UTC
Labels: needs:ops, status:defined

**Comment by chuckharmston** [comment] 2016-05-11 22:32
>  Most of the time is spent in network RTT between users and us-west-2. 

@mostlygeek Isn't that an argument *for* H/2?

Additionally, we're sending tons of consecutive requests as a user types quickly, and 1.1 pipelining blocks each subsequent request, while 2.0 multiplexing runs them parallel. It seems like a much more natural fit.

**Comment by mostlygeek** [comment] 2016-05-11 23:33
> Isn't that an argument for H/2?

No. It's basically time for the packets to make it from the user's laptop to AWS and back. Nothing we can do but put things closer to the user. The protocol won't buy us much in this regard. 

> while 2.0 multiplexing runs them parallel

That is true. How does the plugin handle this out of curiosity when responses arrive out of order?
