### ISSUE TITLE
Consider replacing TLD results with whitelist of top domains

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/universal-search-recommendation#143] opened 2016-05-23 19:27 UTC
We're getting several subpar results that look ad-like:

<img width="469" alt="screen shot 2016-05-23 at 12 21 40 pm" src="https://cloud.githubusercontent.com/assets/23885/15481839/71839b4e-20e1-11e6-96b0-a1c25fc3de47.png">

Perhaps we could be more deliberate about which domains we recommend by restricting it to a whitelist of popular domains. Prospective data sources:
- Alexa Top N
- [Tippy Top Sites](https://github.com/nchapman/tippy-top-sites)

**Comment by chuckharmston** [comment] 2016-05-23 21:28
Good idea, would be good to make this decision based on more complete data, let's come up with a plan to A/B test it and make more data-driven decisions.

Let's shelve it until we can instrument better, possibly 1-2 sprints from now.

**Comment by wresuolc** [comment] 2016-05-23 21:32
https://github.com/mozilla/testpilot/issues/477 is in the current milestone for Test Pilot and would address the a/b test

**Comment by javaun** [comment] 2016-08-31 16:18
Chuck told me that a new bug would likely be a dupe of this one, so I'll put this here and we can decide how to handle it.

We've had several anecdotes of non-top results showing up as our #1 recommendation. Here's a specific case. Users searching in "inbox" see inboxdollars.com as the TLD recommendation, even though in Yahoo search inbox.com is #1 and inboxdollars.com is #3. 

Here's another insight. If you search "inbo" in Yahoo, inboxdollars.com is #1. If you add the "x" and search on "inbox", then inbox.com rises to #1.

In this case we're being to eager to deliver the recommendation before the user gets to a more specific input string. I don't know if that generalizes but it's another facet to what Chuck suggests above (constraining TLDs to top sites). 

Universal Search Result
![screen shot 2016-08-31 at 12 06 32 pm](https://cloud.githubusercontent.com/assets/126270/18137002/bfd2b28a-6f74-11e6-9ffb-13df6f5420e3.png)

"inbo"
![screen shot 2016-08-31 at 12 09 30 pm](https://cloud.githubusercontent.com/assets/126270/18137047/eaa76b5e-6f74-11e6-80dc-dd1475ae6615.png)

"inbox"

![screen shot 2016-08-31 at 12 11 43 pm](https://cloud.githubusercontent.com/assets/126270/18137063/f83670bc-6f74-11e6-8957-446fb4ed8f6c.png)

**Comment by javaun** [comment] 2016-08-31 16:27
The prior comment was an argument for constraining TLD results. Here's a similar issue but for a wikipedia page. Typing "Execu" brings up a Wikipedia page for Executive Order 9066. This is really aggressive because that result isn't even on the first page if you type out "Executive Order". There is also a specific wikipedia page for Executive Order that I'd think should be ahead of it

![screen shot 2016-08-31 at 12 21 55 pm](https://cloud.githubusercontent.com/assets/126270/18137411/38d9ffde-6f76-11e6-871b-935ebd94dad6.png)

**Comment by chuckharmston** [comment] 2016-08-31 16:32
To be clear, this is a case of Yahoo's search results not matching the results we get from Yahoo's APIs. There's very little we will be able to do about this problem as a whole unless we find a new data source; this entire experiment was built on the premise that we can skip any sort of quality scoring by leaning on whatever search engines do.

**Closed** 2016-11-30 16:55 UTC
